// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { SUPABASE_PUBLISHABLE_KEY, SUPABASE_URL } from '@/lib/runtime-config';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

type NoopQueryBuilder = {
  select: (...args: any[]) => NoopQueryBuilder;
  eq: (...args: any[]) => NoopQueryBuilder;
  neq: (...args: any[]) => NoopQueryBuilder;
  order: (...args: any[]) => NoopQueryBuilder;
  limit: (...args: any[]) => NoopQueryBuilder;
  upsert: (...args: any[]) => Promise<{ data: null; error: Error }>;
  insert: (...args: any[]) => Promise<{ data: null; error: Error }>;
  update: (...args: any[]) => Promise<{ data: null; error: Error }>;
  delete: (...args: any[]) => NoopQueryBuilder;
  execute: () => Promise<{ data: null; error: Error }>;
};

function createNoopQueryBuilder(message: string): NoopQueryBuilder {
  const error = new Error(message);
  const builder: NoopQueryBuilder = {
    select: () => builder,
    eq: () => builder,
    neq: () => builder,
    order: () => builder,
    limit: () => builder,
    delete: () => builder,
    upsert: async () => ({ data: null, error }),
    insert: async () => ({ data: null, error }),
    update: async () => ({ data: null, error }),
    execute: async () => ({ data: null, error }),
  };
  return builder;
}

function createNoopSupabaseClient() {
  const message = 'Supabase is not configured. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY.';
  const queryBuilder = createNoopQueryBuilder(message);

  return {
    auth: {
      getSession: async () => ({ data: { session: null }, error: null }),
      onAuthStateChange: () => ({
        data: {
          subscription: {
            unsubscribe: () => undefined,
          },
        },
      }),
      signInWithPassword: async () => ({ data: { user: null, session: null }, error: new Error(message) }),
      signUp: async () => ({ data: { user: null, session: null }, error: new Error(message) }),
      signOut: async () => ({ error: new Error(message) }),
      signInWithOAuth: async () => ({ data: null, error: new Error(message) }),
    },
    from: () => queryBuilder,
    rpc: async () => ({ data: null, error: new Error(message) }),
    channel: () => ({
      on: () => ({
        subscribe: () => ({
          unsubscribe: () => undefined,
        }),
      }),
      subscribe: () => ({
        unsubscribe: () => undefined,
      }),
    }),
    removeChannel: () => undefined,
  } as any;
}

const hasSupabaseConfig = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

import { getAppBuildMode } from '@/lib/portal';

const buildMode = getAppBuildMode();
// Use both buildMode and port number to isolate sessions on localhost
const runtimePort = typeof window !== 'undefined' ? window.location.port : 'default';
const storageKey = `sb-adarsh-oxford-${buildMode}-${runtimePort}`;

export const supabase = hasSupabaseConfig
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storageKey: storageKey,
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : createNoopSupabaseClient();
